[package]
name = "curser"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.19"
tui-textarea = "0.2"
crossterm = { version = "0.25", features = ["event-stream"] }
tokio = { version = "1.25", features = ["full"] }
tokio-stream = "0.1"
fastrand = "1.9.0"
